// -------------------------------------------------------------------------
// double mvd(double f_mass4l,
//            double f_D_bkg_kin);
//      :    :
// To build libm4lmela.so do
//   make -f m4lmela_makefile
//
// To call from C++
//   gSystem->Load("libm4lmela.so");
//      :    :
//   m4lmela mvd;
//   double D = mvd(...);
//
// Fromm Python
//   gSystem.Load("libm4lmela.so");
//      :    :
//   mvd = m4lmela()
//   D = mvd(...)
//
// created: Mon May  1 12:16:01 2017
// -------------------------------------------------------------------------
// 
//
// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/04       [395268]
Creator        : harry
Date           : Mon May  1 12:14:02 2017
Host           : Darwin Harrisons-MBP.centurylink.net 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
Dir            : /Users/harry/Projects/Higgs/monoHZZ4L/Run2016/tmva/m4lmela
Training events: 5000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
f_mass4l                      f_mass4l                      f_mass4l                      f_mass4l                                                        'D'    [73.1200027466,1142]
f_D_bkg_kin                   f_D_bkg_kin                   f_D_bkg_kin                   f_D_bkg_kin                                                     'D'    [4.72300007459e-06,0.988499999046]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>
#include <map>
#include <algorithm>

namespace __m4lmela {

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:
  std::vector<std::string> varnames;
  std::vector<std::string> variables() { return varnames; }


   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_mass4l", "f_D_bkg_kin" };

      varnames.clear();
      varnames.resize(2);
      std::copy(inputVars, inputVars+2, varnames.begin());
    

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][2];
   double fMax_1[3][2];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][3];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 3; fWeights[0] = new double[3]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -69.0058326223133;
   fWeightMatrix0to1[1][0] = 3.09385764040475;
   fWeightMatrix0to1[2][0] = 55.1645842154494;
   fWeightMatrix0to1[3][0] = -41.756725577432;
   fWeightMatrix0to1[4][0] = 7.49227752359188;
   fWeightMatrix0to1[5][0] = -14.7006388871389;
   fWeightMatrix0to1[6][0] = 4.15426884905537;
   fWeightMatrix0to1[7][0] = 5.94016065329702;
   fWeightMatrix0to1[8][0] = 5.91645399488595;
   fWeightMatrix0to1[9][0] = -7.80820138929059;
   fWeightMatrix0to1[0][1] = -0.00692162416089892;
   fWeightMatrix0to1[1][1] = 1.46388116747729;
   fWeightMatrix0to1[2][1] = -0.242746564615899;
   fWeightMatrix0to1[3][1] = 2.60383889718212;
   fWeightMatrix0to1[4][1] = -18.1748988633555;
   fWeightMatrix0to1[5][1] = -7.09569445517588;
   fWeightMatrix0to1[6][1] = -12.2698757625535;
   fWeightMatrix0to1[7][1] = 4.7319489060937;
   fWeightMatrix0to1[8][1] = -1.19634698635426;
   fWeightMatrix0to1[9][1] = 18.522119971292;
   fWeightMatrix0to1[0][2] = -63.9476579127131;
   fWeightMatrix0to1[1][2] = -5.65780036167266;
   fWeightMatrix0to1[2][2] = 50.8251398969107;
   fWeightMatrix0to1[3][2] = 1.2182569997985;
   fWeightMatrix0to1[4][2] = -1.6543974018364;
   fWeightMatrix0to1[5][2] = 23.729271427058;
   fWeightMatrix0to1[6][2] = -1.36648662355571;
   fWeightMatrix0to1[7][2] = -2.89110733096916;
   fWeightMatrix0to1[8][2] = -6.19928704793746;
   fWeightMatrix0to1[9][2] = -2.23480706327165;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -62.3165277712129;
   fWeightMatrix1to2[0][1] = -1.71951402406984;
   fWeightMatrix1to2[0][2] = -63.8847416823637;
   fWeightMatrix1to2[0][3] = 29.6898408373925;
   fWeightMatrix1to2[0][4] = -16.1178781845377;
   fWeightMatrix1to2[0][5] = 6.62109276931216;
   fWeightMatrix1to2[0][6] = 20.9048046435434;
   fWeightMatrix1to2[0][7] = 3.47951699144096;
   fWeightMatrix1to2[0][8] = 3.05665425186364;
   fWeightMatrix1to2[0][9] = 4.40462472192823;
   fWeightMatrix1to2[0][10] = 20.4342785827178;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 75.9599990845;
   fMax_1[0][0] = 580.5;
   fMin_1[1][0] = 73.1200027466;
   fMax_1[1][0] = 1142;
   fMin_1[2][0] = 73.1200027466;
   fMax_1[2][0] = 1142;
   fMin_1[0][1] = 0.000457499991171;
   fMax_1[0][1] = 0.988499999046;
   fMin_1[1][1] = 4.72300007459e-06;
   fMax_1[1][1] = 0.988099992275;
   fMin_1[2][1] = 4.72300007459e-06;
   fMax_1[2][1] = 0.988499999046;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 2;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<2;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}

// Instantiate an  object
std::string ivars[] = {"f_mass4l",
                       "f_D_bkg_kin"};
std::vector<std::string> iivars(ivars, ivars + 2);
};


// -------------------------------------------------------------------------

struct m4lmela : public __m4lmela::ReadMLP
{
  m4lmela() : __m4lmela::ReadMLP(__m4lmela::iivars) {}
  ~m4lmela() {}

  double operator()(std::vector<double>& inputVars)
  {
    return GetMvaValue(inputVars);
  }

  double operator()(double f_mass4l,
                    double f_D_bkg_kin)
  {
    std::vector<double> inputVars(2);
    inputVars[0]	= f_mass4l;
    inputVars[1]	= f_D_bkg_kin;
    return GetMvaValue(inputVars);
  }
};
    